/*
** EPITECH PROJECT, 2023
** B-OOP-400-PAR-4-1-arcade-hugo.mouraud
** File description:
** Event
*/

#ifndef EVENT_HPP_
    #define EVENT_HPP_

namespace arcade {
    /**
     * @enum Event
     * @brief Enumeration containing the list of events that can be generated by the user.
     */
    enum Event {
        none, ///< No event generated.
        a, b, c, d, e, f, g, h, i, j, k, l, m,
        n, o, p, q, r, s, t, u, v, w, x, y, z, ///< Alphabet keys.
        enter, ///< "Enter" key.
        up, ///< Up arrow key.
        down, ///< Down arrow key.
        left, ///< Left arrow key.
        right, ///< Right arrow key.
        fire_1, ///< Fire 1 key.
        fire_2, ///< Fire 2 key.
        spe_1, ///< Special 1 key.
        spe_2, ///< Special 2 key.
        escape, ///< "Escape" key.
        backspace, ///< "Backspace" key.
    };
}

#endif /* !EVENT_HPP_ */
