##
## EPITECH PROJECT, 2023
## B-OOP-400-PAR-4-1-arcade-hugo.mouraud
## File description:
## Makefile
##

all:
	make -C ./src/Pacman
	make -C ./src/Snake

clean:
	make clean -C ./src/Pacman
	make clean -C ./src/Snake

fclean: clean
	make fclean -C ./src/Pacman
	make fclean -C .//src/Snake

re: fclean all

.PHONY: all clean fclean re
